### ISSUE TITLE
Generare una nuova immagine per virtuoso

### ISSUE THREAD

**Issue by bruno-marino** [ioggstream/json-semantic-playground#26]
Lanciando il comando _docker-compose -f docker-compose-test.yml up_ si ottiene questo errore:

Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "git": executable file not found in $PATH: unknown

Lanciando il comando _docker-compose -f docker-compose.yaml up_ si ottiene questo errore:

Error response from daemon: manifest for teamdigitale/pdnd-ontopia-virtuoso:latest not found: manifest unknown: manifest unknown

Sono necessari degli step aggiuntivi per lanciare la build dei container?

**Comment by ioggstream** [comment]
> exec: "git": executable file not found in $PATH: unknown

Puoi provare ora su docker-compose-test.yaml? Ho risistemato i file, ma In generale quello è un file di esempio per far vedere come configurare una pipeline con docker-compose.

> Error response from daemon: manifest for teamdigitale/pdnd-ontopia-virtuoso:latest not found: manifest unknown: manifest unknown

Credo dipenda dalla versione di docker che stai usando: qual è? Se non funziona devi rifare la build di teamdigitale/pdnd-ontopia-virtuoso

**Comment by bruno-marino** [comment]
> > exec: "git": executable file not found in $PATH: unknown
> 
> Puoi provare ora su docker-compose-test.yaml? Ho risistemato i file, ma In generale quello è un file di esempio per far vedere come configurare una pipeline con docker-compose.

Ora ottengo questo:



json-semantic-playground-zero-1      | black....................................................................Failed
json-semantic-playground-zero-1      | - hook id: black
json-semantic-playground-zero-1      | - exit code: 1
json-semantic-playground-zero-1      |
json-semantic-playground-zero-1      | Traceback (most recent call last):
json-semantic-playground-zero-1      |   File "/root/.cache/pre-commit/repohygkxtbw/py_env-python3.9/bin/black", line 8, in <module>
json-semantic-playground-zero-1      |     sys.exit(patched_main())
json-semantic-playground-zero-1      |   File "/root/.cache/pre-commit/repohygkxtbw/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1372, in patched_main
json-semantic-playground-zero-1      |     patch_click()
json-semantic-playground-zero-1      |   File "/root/.cache/pre-commit/repohygkxtbw/py_env-python3.9/lib/python3.9/site-packages/black/__init__.py", line 1358, in patch_click
json-semantic-playground-zero-1      |     from click import _unicodefun
json-semantic-playground-zero-1      | ImportError: cannot import name '_unicodefun' from 'click' (/root/.cache/pre-commit/repohygkxtbw/py_env-python3.9/lib/python3.9/site-packages/click/__init__.py)
json-semantic-playground-zero-1      |
json-semantic-playground-zero-1      | isort (python)...........................................................Passed
json-semantic-playground-zero-1      | isort (cython).......................................(no files to check)Skipped
json-semantic-playground-zero-1      | isort (pyi)..........................................(no files to check)Skipped
json-semantic-playground-zero-1      | flake8...................................................................Passed
json-semantic-playground-zero-1      | bandit...................................................................Passed
json-semantic-playground-zero-1      | safety...................................................................Failed
json-semantic-playground-zero-1      | - hook id: python-safety-dependencies-check
json-semantic-playground-zero-1      | - exit code: 1
json-semantic-playground-zero-1      |
json-semantic-playground-zero-1      | Warning: unpinned requirement 'connexion' found in openapi/requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'connexion' found in openapi/requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'openapi-spec-validator' found in openapi/requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'click' found in openapi/requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'sqlalchemy' found in openapi/requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'tornado' found in openapi/requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'flask-cors' found in openapi/requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'connexion' found in requirements-dev.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'connexion' found in requirements-dev.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'requests' found in requirements-dev.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'openapi_resolver' found in requirements-dev.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'pyyaml' found in requirements-dev.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'pytest' found in requirements-dev.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'frictionless' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'rdflib' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'jsonpath_ng' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'requests' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'pyyaml' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'jsonschema' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'pandas' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'pyshacl' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'pyld' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'sqlalchemy' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'requests_cache' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'gitpython' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'openapi_spec_validator' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Warning: unpinned requirement 'click' found in requirements.txt, unable to check.
json-semantic-playground-zero-1      | Unexpected Exception happened: 'NoneType' object has no attribute 'telemetry'
json-semantic-playground-zero-1      | Traceback (most recent call last):
json-semantic-playground-zero-1      |   File "/root/.cache/pre-commit/repol_5ptr0d/py_env-python3.9/lib/python3.9/site-packages/safety/cli.py", line 110, in check
json-semantic-playground-zero-1      |     announcements = safety.get_announcements(key=key, proxy=proxy_dictionary, telemetry=ctx.parent.telemetry)
json-semantic-playground-zero-1      | AttributeError: 'NoneType' object has no attribute 'telemetry'
json-semantic-playground-zero-1      | Unhandled exception happened: 'NoneType' object has no attribute 'telemetry'
json-semantic-playground-zero-1      |
json-semantic-playground-zero-1      | jsonschema...............................................................Passed
json-semantic-playground-zero-1      | pyshacl ontologies.......................................................Passed
json-semantic-playground-zero-1      | Ontologies latest validator..............................................Passed
json-semantic-playground-zero-1      | pyshacl vocabularies.....................................................Passed
json-semantic-playground-zero-1 exited with code 1



> > Error response from daemon: manifest for teamdigitale/pdnd-ontopia-virtuoso:latest not found: manifest unknown: manifest unknown
> 
> Credo dipenda dalla versione di docker che stai usando: qual è? Se non funziona devi rifare la build di teamdigitale/pdnd-ontopia-virtuoso

Sto utilizzando questa versione: Docker version 20.10.17, build 100c701. Confermo che non funziona

**Comment by ioggstream** [comment]
> json-semantic-playground-zero-1 | File "/root/.cache/pre-commit/repohygkxtbw/py_env-python3.9/lib/python3.9/site-packages/black/init.py", line 1358, in patch_click
json-semantic-playground-zero-1 | from click import _unicodefun
json-semantic-playground-zero-1 | ImportError: cannot import name '_unicodefun' from 'click' (/root/.cache/pre-commit/repohygkxtbw/py_env-python3.9/lib/python3.9/site-packages/click/init.py)


`rm deleteme -fr`


> Warning ... 

L'obiettivo del docker-compose-test è di illustrare come eseguire una serie di test in fila, quindi non è un problema in teoria.
Stai cercando di raggiungere qualche obiett

> Sto utilizzando questa versione: Docker version 20.10.17, build 100c701. Confermo che non funziona

dovresti rifare la build in locale di teamdigitale/pdnd-ontopia-virtuoso:latest puoi provare a partire da questa https://github.com/italia/dati-ontopia-virtuoso
perché non possiamo ad oggi sovrascrivere l'immagine su docker hub

**Comment by bruno-marino** [comment]
Sono riuscito  fare la build in localedi di teamdigitale/pdnd-ontopia-virtuoso:latest e ora ad ottenere i seguenti container, rilanciando il comando docker-compose up con lo yaml principale di questo repository:

- json-semantic-playground_lodview_1
- json-semantic-playground_virtuoso-1  
- json-semantic-playground_test-1_1

Visualizzo l'interfaccia di lodview (:9891) vuota e visualizzo l'interfaccia di virtuoso (:8890), non visualizzo interfacce per json-semantic-playground_test-1_1.

Il mio obbiettivo è quello di sperimentare il lavoro svolto in questo repository, in particolare vorrei capire se fosse possibile convertire file owl in yaml.

**Comment by ioggstream** [comment]
@bruno-marino il container test lancia i pre-commit checks ed esce, quindi è corretto così.

I file OWL non sono convertibili in YAML: puoi spiegare meglio l'obiettivo?

Intanto leggi qui un po' di materiale https://docs.google.com/presentation/d/16-u3nN0NuXQRJIxbhpPpHweijEC7eQ3fUaXftIZEGFg/edit#slide=id.g137ea79fc71_0_1

**Comment by ioggstream** [comment]
@bruno-marino puoi fare una PR che genera l'immagine Docker ex novo, pls? :)

**Comment by bruno-marino** [comment]
@ioggstream intendi senza rifare la build in locale di virtuoso? Ho provato ma ottengo sempre questo:

    $ docker-compose up -d
    virtuoso Pulling
    lodview Pulling
    virtuoso Error
    lodview Error
    Error response from daemon: manifest for teamdigitale/pdnd-ontopia-virtuoso:latest not found: manifest unknown: manifest unknown

**Comment by ioggstream** [comment]
Sì, andrebbe aggiunta la build ei virtuoso al compose.

**Comment by bruno-marino** [comment]
Si, avevo fatto la build di virtuoso a parte e aveva funzionato
